name: csv_pdf
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - libffi=3.4.2
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - openssl=3.3.1
  - pip=24.2
  - python=3.10.14
  - setuptools=72.1.0
  - tk=8.6.13
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - backports-unittest-mock==1.5.1
      - certifi==2024.8.30
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - colorama==0.4.6
      - docx2pdf==0.1.8
      - idna==3.10
      - imaplib2==3.6
      - jinja2==3.1.4
      - lxml==5.3.0
      - markdown==3.6
      - markupsafe==2.1.5
      - mock==5.1.0
      - numpy==2.0.1
      - pandas==2.2.2
      - pdfkit==1.0.0
      - pdfrw==0.4
      - pillow==10.4.0
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - pytz==2024.1
      - pywin32==306
      - reportlab==4.2.2
      - requests==2.32.3
      - six==1.16.0
      - tqdm==4.66.5
      - typing-extensions==4.12.2
      - tzdata==2024.1
      - urllib3==2.2.3

